"""Create user table

Revision ID: 622d9cd6dd46
Revises: 9a321525e4c2
Create Date: 2025-03-14 18:01:49.461139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622d9cd6dd46'
down_revision = '9a321525e4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_mean', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('voice_std', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('voice_std')
        batch_op.drop_column('voice_mean')

    # ### end Alembic commands ###
