"""Replace voice_template with speaker_embedding

Revision ID: d498c37b7ef8
Revises: 622d9cd6dd46
Create Date: 2025-03-17 13:47:50.745307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd498c37b7ef8'
down_revision = '622d9cd6dd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker_embedding', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('voice_mean')
        batch_op.drop_column('voice_template')
        batch_op.drop_column('voice_data')
        batch_op.drop_column('voice_std')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_std', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('voice_data', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('voice_template', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('voice_mean', sa.BLOB(), nullable=True))
        batch_op.drop_column('speaker_embedding')

    # ### end Alembic commands ###
